// Generated by xdsl-ccpp. Array arguments are column-major (Fortran order).
// Pass Kokkos::View with LayoutLeft, or transpose before calling.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif

void Kessler_chost_physics_register(
    char*            errmsg,
    int*             errflg 
);

void Kessler_chost_physics_initialize(
    char*            errmsg,
    int*             errflg 
);

void Kessler_chost_physics_finalize(
    char*            errmsg,
    int*             errflg 
);

void Kessler_chost_physics_run(
    int              ncol,
    int              nz,
    double           dt,
    int              lyr_surf,
    int              lyr_toa,
    const double*    cpair,
    const double*    rair,
    const double*    rho,
    const double*    z_mid,
    const double*    exner,
    double*          theta,
    double*          qv,
    double*          qc,
    double*          qr,
    double*          precl,
    double*          relhum,
    const double*    temp_prev,
    double*          temp_tend,
    char*            scheme_name,
    char*            errmsg,
    int*             errflg 
);

void Kessler_chost_physics_timestep_initial(
    int              ncol,
    int              nz,
    const double*    temp,
    double*          temp_prev,
    double*          temp_tend,
    char*            errmsg,
    int*             errflg 
);

void Kessler_chost_physics_timestep_final(
    int              ncol,
    int              nz,
    const double*    cpair,
    const double*    temp,
    const double*    z_mid,
    const double*    phis,
    double*          st_energy,
    char*            errmsg,
    int*             errflg 
);

void Kessler_chost_physics_physics_initial(
    double           lv,
    double           pref,
    double           rhoqr,
    double           gravit,
    char*            errmsg,
    int*             errflg 
);

void Kessler_chost_physics_physics_final(
    char*            errmsg,
    int*             errflg 
);

#ifdef __cplusplus
}
#endif
