// Generated by xdsl-ccpp. Array arguments are column-major (Fortran order).
// Pass Kokkos::View with LayoutLeft, or transpose before calling.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif

void Kessler_ccpp_physics_register(
    const char*      suite_name,
    char*            errmsg,
    int*             errflg 
);

void Kessler_ccpp_physics_initialize(
    const char*      suite_name,
    char*            errmsg,
    int*             errflg 
);

void Kessler_ccpp_physics_finalize(
    const char*      suite_name,
    char*            errmsg,
    int*             errflg 
);

void Kessler_ccpp_physics_timestep_initial(
    const char*      suite_name,
    char*            errmsg,
    int*             errflg 
);

void Kessler_ccpp_physics_timestep_final(
    const char*      suite_name,
    char*            errmsg,
    int*             errflg 
);

void Kessler_ccpp_physics_run(
    const char*      suite_name,
    const char*      suite_part,
    int              col_start,
    int              col_end,
    char*            errmsg,
    int*             errflg 
);

#ifdef __cplusplus
}
#endif
