// Generated by xdsl-ccpp. C++ ergonomics wrapper for Kessler_ccpp_chost_cap.
// Array arguments are column-major (Fortran order).
#pragma once
#include <string>
#include <vector>
#include "Kessler_ccpp_chost_cap.h"

namespace Kessler_chost {

struct Status {
    int         code;
    std::string message;
    bool ok() const { return code == 0; }
};

// ── register ────────────────────────────────────────────────────────────────

inline Status do_register() {
    char   errmsg[513]      = {};
    int    errflg           = 0;
    Kessler_chost_physics_register(errmsg, &errflg);
    return {errflg, errflg ? errmsg : ""};
}

// ── initialize ──────────────────────────────────────────────────────────────

struct InitializeArgs {
    double           lv;
    double           pref;
    double           rhoqr;
    double           gravit;
};

inline Status initialize(const InitializeArgs& a) {
    char   errmsg[513]      = {};
    int    errflg           = 0;
    Kessler_chost_physics_initialize(
        a.lv, a.pref, a.rhoqr, a.gravit,
        errmsg, &errflg
    );
    return {errflg, errflg ? errmsg : ""};
}

// ── finalize ────────────────────────────────────────────────────────────────

inline Status finalize() {
    char   errmsg[513]      = {};
    int    errflg           = 0;
    Kessler_chost_physics_finalize(errmsg, &errflg);
    return {errflg, errflg ? errmsg : ""};
}

// ── timestep_initial ────────────────────────────────────────────────────────

struct TimestepInitialArgs {
    int              ncol;
    int              nz;
    const double*    temp;
    double*          temp_prev;
    double*          temp_tend;
};

inline Status timestep_initial(const TimestepInitialArgs& a) {
    char   errmsg[513]      = {};
    int    errflg           = 0;
    Kessler_chost_physics_timestep_initial(
        a.ncol, a.nz, a.temp, a.temp_prev,
        a.temp_tend, errmsg, &errflg
    );
    return {errflg, errflg ? errmsg : ""};
}

// ── timestep_final ──────────────────────────────────────────────────────────

struct TimestepFinalArgs {
    int              ncol;
    int              nz;
    const double*    cpair;
    const double*    temp;
    const double*    z_mid;
    const double*    phis;
    double*          st_energy;
};

inline Status timestep_final(const TimestepFinalArgs& a) {
    char   errmsg[513]      = {};
    int    errflg           = 0;
    Kessler_chost_physics_timestep_final(
        a.ncol, a.nz, a.cpair, a.temp,
        a.z_mid, a.phis, a.st_energy, errmsg,
        &errflg
    );
    return {errflg, errflg ? errmsg : ""};
}

// ── run ─────────────────────────────────────────────────────────────────────

struct RunArgs {
    int              ncol;
    int              nz;
    int              col_start;
    int              col_end;
    double           dt;
    int              lyr_surf;
    int              lyr_toa;
    const double*    cpair;
    const double*    rair;
    const double*    rho;
    const double*    z_mid;
    const double*    exner;
    double*          theta;
    double*          qv;
    double*          qc;
    double*          qr;
    double*          precl;
    double*          relhum;
    const double*    temp_prev;
    double*          temp_tend;
};

inline Status run(const RunArgs& a) {
    char   scheme_name[65]  = {};
    char   errmsg[513]      = {};
    int    errflg           = 0;
    Kessler_chost_physics_run(
        a.ncol, a.nz, a.col_start, a.col_end,
        a.dt, a.lyr_surf, a.lyr_toa, a.cpair,
        a.rair, a.rho, a.z_mid, a.exner,
        a.theta, a.qv, a.qc, a.qr,
        a.precl, a.relhum, a.temp_prev, a.temp_tend,
        scheme_name, errmsg, &errflg
    );
    return {errflg, errflg ? errmsg : ""};
}

// ── State ─────────────────────────────────────────────────────────────────────

struct State {
    double           lv = 0;
    double           pref = 0;
    double           rhoqr = 0;
    double           gravit = 0;
    int              ncol = 0;
    int              nz = 0;
    double*          temp = nullptr;
    double*          temp_prev = nullptr;
    double*          temp_tend = nullptr;
    double*          cpair = nullptr;
    double*          z_mid = nullptr;
    double*          phis = nullptr;
    double*          st_energy = nullptr;
    double           dt = 0;
    int              lyr_surf = 0;
    int              lyr_toa = 0;
    double*          rair = nullptr;
    double*          rho = nullptr;
    double*          exner = nullptr;
    double*          theta = nullptr;
    double*          qv = nullptr;
    double*          qc = nullptr;
    double*          qr = nullptr;
    double*          precl = nullptr;
    double*          relhum = nullptr;

    State(int ncol = 0, int nz = 0)
        : ncol(ncol), nz(nz) {}

    // Allocate all array fields from internal storage.
    // Set ncol (and nz/ncnst for higher-rank arrays) before calling.
    void allocate() {
        _temp.assign(static_cast<std::size_t>(ncol) * nz, 0);
        temp = _temp.data();
        _temp_prev.assign(static_cast<std::size_t>(ncol) * nz, 0);
        temp_prev = _temp_prev.data();
        _temp_tend.assign(static_cast<std::size_t>(ncol) * nz, 0);
        temp_tend = _temp_tend.data();
        _cpair.assign(static_cast<std::size_t>(ncol) * nz, 0);
        cpair = _cpair.data();
        _z_mid.assign(static_cast<std::size_t>(ncol) * nz, 0);
        z_mid = _z_mid.data();
        _phis.assign(static_cast<std::size_t>(ncol), 0);
        phis = _phis.data();
        _st_energy.assign(static_cast<std::size_t>(ncol) * nz, 0);
        st_energy = _st_energy.data();
        _rair.assign(static_cast<std::size_t>(ncol) * nz, 0);
        rair = _rair.data();
        _rho.assign(static_cast<std::size_t>(ncol) * nz, 0);
        rho = _rho.data();
        _exner.assign(static_cast<std::size_t>(ncol) * nz, 0);
        exner = _exner.data();
        _theta.assign(static_cast<std::size_t>(ncol) * nz, 0);
        theta = _theta.data();
        _qv.assign(static_cast<std::size_t>(ncol) * nz, 0);
        qv = _qv.data();
        _qc.assign(static_cast<std::size_t>(ncol) * nz, 0);
        qc = _qc.data();
        _qr.assign(static_cast<std::size_t>(ncol) * nz, 0);
        qr = _qr.data();
        _precl.assign(static_cast<std::size_t>(ncol), 0);
        precl = _precl.data();
        _relhum.assign(static_cast<std::size_t>(ncol) * nz, 0);
        relhum = _relhum.data();
    }

private:
    std::vector<double> _temp;
    std::vector<double> _temp_prev;
    std::vector<double> _temp_tend;
    std::vector<double> _cpair;
    std::vector<double> _z_mid;
    std::vector<double> _phis;
    std::vector<double> _st_energy;
    std::vector<double> _rair;
    std::vector<double> _rho;
    std::vector<double> _exner;
    std::vector<double> _theta;
    std::vector<double> _qv;
    std::vector<double> _qc;
    std::vector<double> _qr;
    std::vector<double> _precl;
    std::vector<double> _relhum;
};

inline Status initialize(const State& s) {
    return initialize({
        .lv=s.lv,
        .pref=s.pref,
        .rhoqr=s.rhoqr,
        .gravit=s.gravit,
    });
}

inline Status timestep_initial(const State& s) {
    return timestep_initial({
        .ncol=s.ncol,
        .nz=s.nz,
        .temp=s.temp,
        .temp_prev=s.temp_prev,
        .temp_tend=s.temp_tend,
    });
}

inline Status timestep_final(const State& s) {
    return timestep_final({
        .ncol=s.ncol,
        .nz=s.nz,
        .cpair=s.cpair,
        .temp=s.temp,
        .z_mid=s.z_mid,
        .phis=s.phis,
        .st_energy=s.st_energy,
    });
}

inline Status run(const State& s, int col_start, int col_end) {
    return run({
        .ncol=s.ncol,
        .nz=s.nz,
        .col_start=col_start,
        .col_end=col_end,
        .dt=s.dt,
        .lyr_surf=s.lyr_surf,
        .lyr_toa=s.lyr_toa,
        .cpair=s.cpair,
        .rair=s.rair,
        .rho=s.rho,
        .z_mid=s.z_mid,
        .exner=s.exner,
        .theta=s.theta,
        .qv=s.qv,
        .qc=s.qc,
        .qr=s.qr,
        .precl=s.precl,
        .relhum=s.relhum,
        .temp_prev=s.temp_prev,
        .temp_tend=s.temp_tend,
    });
}

} // namespace Kessler_chost
