// Generated by xdsl-ccpp. Array arguments are column-major (Fortran order).
// Pass Kokkos::View with LayoutLeft, or transpose before calling.
#pragma once
#ifdef __cplusplus
extern "C" {
#endif

void ccpp_register(
    const char*      suite_name,  /* null-terminated string, any length */
    char*            errmsg,  /* caller must allocate >= 513 bytes (512 + null terminator) */
    int*             errflg 
);

void ccpp_init(
    const char*      suite_name,  /* null-terminated string, any length */
    char*            errmsg,  /* caller must allocate >= 513 bytes (512 + null terminator) */
    int*             errflg 
);

void ccpp_final(
    const char*      suite_name,  /* null-terminated string, any length */
    char*            errmsg,  /* caller must allocate >= 513 bytes (512 + null terminator) */
    int*             errflg 
);

void ccpp_physics_run(
    const char*      suite_name,  /* null-terminated string, any length */
    const char*      suite_part,  /* null-terminated string, any length */
    int              col_start,
    int              col_end,
    char*            errmsg,  /* caller must allocate >= 513 bytes (512 + null terminator) */
    int*             errflg 
);

void ccpp_physics_timestep_init(
    const char*      suite_name,  /* null-terminated string, any length */
    const char*      suite_part,  /* null-terminated string, any length */
    int              col_start,
    int              col_end,
    char*            errmsg,  /* caller must allocate >= 513 bytes (512 + null terminator) */
    int*             errflg 
);

void ccpp_physics_timestep_final(
    const char*      suite_name,  /* null-terminated string, any length */
    const char*      suite_part,  /* null-terminated string, any length */
    int              col_start,
    int              col_end,
    char*            errmsg,  /* caller must allocate >= 513 bytes (512 + null terminator) */
    int*             errflg 
);

void ccpp_physics_init(
    const char*      suite_name,  /* null-terminated string, any length */
    const char*      suite_part,  /* null-terminated string, any length */
    int              col_start,
    int              col_end,
    char*            errmsg,  /* caller must allocate >= 513 bytes (512 + null terminator) */
    int*             errflg 
);

void ccpp_physics_final(
    const char*      suite_name,  /* null-terminated string, any length */
    const char*      suite_part,  /* null-terminated string, any length */
    int              col_start,
    int              col_end,
    char*            errmsg,  /* caller must allocate >= 513 bytes (512 + null terminator) */
    int*             errflg 
);

#ifdef __cplusplus
}
#endif
